language: generic
services:
  - docker
env:
  - >-
    DEPENDENCY_PACKAGES="meson desktop-file-utils appstream-util libglib2.0-bin
    gettext python3 libgee-0.8-dev libglib2.0-dev libgtk-3-dev
    libgit2-glib-1.0-dev valac"
script:
  - >-
    docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c
    "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd
    /tmp/build-dir && meson build && ninja -C build test"
  - >-
    docker run -v "$PWD":/tmp/build-dir elementary/docker:loki-unstable /bin/sh
    -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd
    /tmp/build-dir && meson build && ninja -C build test"
  - >-
    docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh
    -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd
    /tmp/build-dir && meson build && ninja -C build test"
  - 'docker run -v "$PWD":/var/opt/vala-lint elementary/docker:vala-lint'
